default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: meetup_development
  host: localhost
  username: postgres
  password: root

production:
  <<: *default
  database: meetup_test_production
